project_gymnasium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static

from project_gymnasium import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'users.views.error404'
handler500 = 'users.views.error500'

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

    # Customers Urls
    path('customers/register', views.post_customer, name='post_customer'),
    path('customers', views.get_all_customers, name='get_all_customers'),
    path('customer/<int:customer_id>/details', views.get_customer, name='get_customer'),
    path('customer/<int:customer_id>/edit/<str:edit_type>', views.put_customer, name='put_customer'),
    path('customer/<int:customer_id>/delete', views.delete_customer, name='delete_customer'),

    # User Urls
    path('user/<int:user_id>/details', views.get_user, name='get_user'),
]

users/models.py
import uuid

from django.db import models

Gender_Choices = (('M', 'Male'), ('F', 'Female'))
Status_Choices = ((1, 'Active'), (0, 'Inactive'))


# Create your models here
class User(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=10)
    gender = models.CharField(max_length=1, choices=Gender_Choices)
    address = models.CharField(max_length=100)
    gym_name = models.CharField(max_length=30)
    gym_address = models.CharField(max_length=100)
    gym_contact_no = models.CharField(max_length=10)

    def __str__(self):
        return f'User : {self.id} | Name : {self.name} | Gym : {self.gym_name}'


class UserAuth(models.Model):
    token = models.CharField(default=str(uuid.uuid4), max_length=36, editable=False)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    user = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        return f"{self.user} | {self.username}"


class Customer(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=40)
    contact_no = models.CharField(max_length=10)
    email = models.CharField(max_length=50)
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=Gender_Choices)
    proof_id_no = models.CharField(max_length=20)
    address = models.TextField(max_length=100)
    user = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        return f'Customer : {self.name} (Id : {self.id})'


class CustomerStatus(models.Model):
    customer = models.ForeignKey(Customer, models.CASCADE, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    start_date = models.DateField()
    end_date = models.DateField()
    total_fees = models.IntegerField()
    fees_paid = models.IntegerField()
    fees_remaining = models.IntegerField()
    status = models.IntegerField(choices=Status_Choices)

    def __str__(self):
        return f'Customer: {self.customer} | Status : {self.status}'

users/forms.py
import datetime

from django import forms
from django.forms import Select

from users.models import Customer, CustomerStatus

Gender_Choices = ((None, 'Select the Gender'), ('M', 'Male'), ('F', 'Female'))


class DateInput(forms.DateInput):
    input_type = 'date'


class Select(Select):
    def create_option(self, *args, **kwargs):
        option = super().create_option(*args, **kwargs)
        if not option.get('value'):
            option['attrs']['disabled'] = True
            option['attrs']['hidden'] = True
        return option


class CustomerForm(forms.ModelForm):
    name = forms.CharField(label='Name',
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
                           required=True,
                           max_length=40)
    contact_no = forms.CharField(label='Contact No',
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Contact No.'}),
                                 required=True,
                                 max_length=10)
    email = forms.CharField(label='Email address',
                            widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
                            required=False,
                            max_length=50)
    dob = forms.DateField(label='Date of Birth',
                          initial='2000-01-01',
                          widget=DateInput(attrs={'class': 'form-control'}),
                          required=True)
    gender = forms.ChoiceField(label='Gender',
                               initial='',
                               choices=Gender_Choices,
                               widget=Select(attrs={'class': 'form-control'}),
                               required=True
                               )
    proof_id_no = forms.CharField(label='Adhar No',
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adhar No.'}),
                                  required=True,
                                  max_length=20
                                  )
    address = forms.CharField(label='Address',
                              widget=forms.Textarea(
                                  attrs={'class': 'form-control', 'rows': '4', 'placeholder': 'Address'}),
                              required=True,
                              max_length=100
                              )

    class Meta:
        model = Customer
        fields = ['name', 'contact_no', 'email', 'dob', 'gender', 'proof_id_no', 'address']


class CustomerStatusForm(forms.ModelForm):
    start_date = forms.DateField(label='Start Date',
                                 initial=datetime.date.today,
                                 widget=DateInput(attrs={'class': 'form-control'}),
                                 required=True)
    end_date = forms.DateField(label='Closing Date',
                               initial=datetime.date.today,
                               widget=DateInput(attrs={'class': 'form-control'}),
                               required=True)
    total_fees = forms.IntegerField(label='Total Fees',
                                    widget=forms.NumberInput(
                                        attrs={'class': 'form-control', 'placeholder': 'Total Fees'}),
                                    required=True
                                    )
    fees_paid = forms.IntegerField(label='Paid Fees',
                                   widget=forms.NumberInput(
                                       attrs={'class': 'form-control', 'placeholder': 'Paid Fees'}),
                                   required=True
                                   )
    fees_remaining = forms.IntegerField(label='Remaining Fees',
                                        widget=forms.NumberInput(
                                            attrs={'class': 'form-control', 'placeholder': 'Remaining Fees',
                                                   'readonly': True}),
                                        required=True
                                        )

    class Meta:
        model = CustomerStatus
        fields = ['start_date', 'end_date', 'total_fees', 'fees_paid', 'fees_remaining']

users/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from project_gymnasium import settings
from users.forms import CustomerForm, CustomerStatusForm
from users.models import CustomerStatus, Customer, UserAuth, User
from users.validation import get_dashboard_data, is_authenticated, put_customer_post, \
    put_customer_get, get_user_data, post_customer_save, set_login_session


def error404(request, exception):
    return render(request, 'error_404.html')


def error500(request):
    return render(request, 'error_500.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            instance_user_auth = UserAuth.objects.get(username=username, password=password)
            if request.POST.get('stay_login'):
                request.session.set_expiry(None)
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
            else:
                request.session.set_expiry(600)
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
            set_login_session(instance_user_auth, request)
            return redirect('dashboard')
        except ObjectDoesNotExist:
            messages.error(request, 'Username or Password is incorrect')
    return render(request, 'login.html')


def logout(request):
    if not is_authenticated(request): redirect('login')
    try:
        del request.session['user_token']
        del request.session['user_id']
    except KeyError:
        pass
    return render(request, 'logout.html')


def dashboard(request):
    if not is_authenticated(request): return redirect('login')
    user_id = request.session['user_id']
    data = get_dashboard_data(user_id)
    return render(request, 'dashboard.html', {'data': data, 'user': get_user_data(request)})


def post_customer(request):
    if not is_authenticated(request): return redirect('login')
    user_id = request.session['user_id']
    page = 'register'
    if request.method == 'POST':
        if 'cancel' in request.POST: return redirect('dashboard')
        instance = Customer(user=User.objects.get(id=user_id))
        form_basic = CustomerForm(data=request.POST, instance=instance)
        form_status = CustomerStatusForm(request.POST)
        if form_basic.is_valid() and form_status.is_valid():
            post_customer_save(form_basic, request)
            return redirect('dashboard')
    else:
        form_basic = CustomerForm()
        form_status = CustomerStatusForm()
    return render(request, 'customer_register.html',
                  {'form_basic': form_basic, 'form_status': form_status, 'page': page, 'user': get_user_data(request)})


def get_all_customers(request):
    if not is_authenticated(request): return redirect('login')
    user_id = request.session['user_id']
    if request.method == 'GET':
        instance_objects = CustomerStatus.objects.filter(customer__user=user_id).select_related() \
            .order_by('customer__name')
        status = request.GET.get('status', None)
        if status:
            instance_objects=instance_objects.filter(status=status)
        return render(request, 'customer_all.html', {'objects': instance_objects, 'user': get_user_data(request)})
    return redirect('dashboard')


def get_customer(request, customer_id):
    if not is_authenticated(request): return redirect('login')
    user_id = request.session['user_id']
    instance_object = CustomerStatus.objects.filter(customer__id=customer_id, customer__user=user_id).select_related()
    return render(request, 'customer_profile.html', {'object': instance_object[0], 'user': get_user_data(request)})


def put_customer(request, customer_id, edit_type):
    if not is_authenticated(request): return redirect('login')
    if request.method == 'POST':
        if 'cancel' in request.POST: return redirect('get_customer', customer_id=customer_id)
        return put_customer_post(request, customer_id, edit_type)
    else:
        return put_customer_get(request, customer_id, edit_type)


def delete_customer(request, customer_id):
    if not is_authenticated(request): return redirect('login')
    user_id = request.session['user_id']
    try:
        Customer.objects.get(id=customer_id, user=user_id).delete()
        messages.success(request, 'Customer deleted successfully')
        return redirect('get_all_customers')
    except ObjectDoesNotExist:
        messages.error(request, 'Something went wrong')
        return redirect('get_customer', customer_id=customer_id)


def get_user(request, user_id):
    if not is_authenticated(request): return redirect('login')
    if user_id == request.session['user_id']:
        instance_object = User.objects.get(id=user_id).__dict__
        return render(request, 'user_profile.html', {'object': instance_object, 'user': get_user_data(request)})
    else:
        messages.error(request, 'Something went wrong')
        return redirect('dashboard')

users/templates/base.html
{% load static %}
{% block styles %}

{% endblock %}
{% static 'assets/images' as baseImages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    <link rel="shortcut icon" href="{{baseImages}}/favicon.png"/>
</head>
<body>
{% block base %}


{% endblock %}

<script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="{% static 'assets/js/off-canvas.js' %}"></script>
<script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'assets/js/misc.js' %}"></script>
<script src="{% static 'assets/js/jquery-latest.js' %}"></script>
<script type="text/javascript">
      $(document).ready( function() {
        $('#deletesuccess').delay(1000).fadeOut();
      });
</script>
<script type="text/javascript">
    function changeClass(){
       var element = document.getElementById('fullscreen-button');
       if(element.classList.contains("mdi-fullscreen")){
          element.classList.remove("mdi-fullscreen");
          element.classList.add("mdi-fullscreen-exit");
       }
       else
       {
          element.classList.remove("mdi-fullscreen-exit");
          element.classList.add("mdi-fullscreen");
       }
    }
</script>
{% block scripts %}


{% endblock %}
</body>
</html>

users/templates/customer_register.html
{% extends 'index.html' %}
{% block styles %}
<style>
.border-red {
 border-color: red !important;
}
</style>
{% endblock %}
{% block index %}
<title>{{page | title  }} Customer</title>
<div class="page-header">
  <h3 class="page-title">
    <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-account-plus"></i>
    </span> {{page | title  }} Customer </h3>
  <nav aria-label="breadcrumb">
    <ul class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">
        <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
      </li>
    </ul>
  </nav>
</div>
<div class="row">
  <div class="col-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Fill the customer details</h4>
        <p class="card-description"> {{msg}} </p>
        <form id="form" class="forms-sample" method="post">
          {% csrf_token %}
          <div class="row">
            {% if page == 'register' or edit_type == 'basic' %}
            <div class="col-lg-6">
              <p class="card-description">Basic Details</p>
              {{form_basic.as_p}}
            </div>
            {% endif %}
            {% if page == 'register' or edit_type == 'status' %}
            <div class="col-lg-6">
              <p class="card-description">Customer Status </p>
              {{form_status.as_p}}
              <div class="form-group row">
                <label class="col-sm-3 col-form-label">Membership</label>
                <div class="col-sm-4">
                  <div class="form-check">
                    <label class="form-check-label">
                      <input type="radio" class="form-check-input" name="status" id="membershipRadios1" value="1" {% if status %} checked {% endif %}> Active </label>
                  </div>
                </div>
                <div class="col-sm-5">
                  <div class="form-check">
                    <label class="form-check-label">
                      <input type="radio" class="form-check-input" name="status" id="membershipRadios2" value="0" {% if not status %} checked {% endif %}> Inactive </label>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
          <!--                    {% for field in form %}-->
          <!--                    <div class="form-group">-->
          <!--                        <label>{{field.label}}</label>-->
          <!--                        {{field}}-->
          <!--                        {{field.error}}-->
          <!--                    </div>-->
          <!--                    {% endfor %}-->
          {% if page == 'register' %}
          <button type="submit" form="form" formaction="{% url 'post_customer' %}" formmethod="post" class="btn btn-gradient-primary mr-2">Submit</button>
          {% elif page == 'update' %}
          <button type="submit" form="form" formaction="{% url 'put_customer' customer_id=customer_id edit_type=edit_type  %}" formmethod="post" class="btn btn-gradient-primary mr-2">Update</button>
          {% endif %}
          <button class="btn btn-light" formnovalidate name="cancel" value="cancel">Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
<script>
  $(function() {
    $("#id_total_fees, #id_fees_paid").on("keydown keyup", function() {
      $("#id_fees_remaining").val(Number($("#id_total_fees").val()) - Number($("#id_fees_paid").val()));
    })

    $('#id_name').on('input blur paste', function() {
      if ( $(this).val().match(/^[a-zA-Z ]*$/)) {
      console.log('IF',$(this).val());
        $(this).removeClass("border-red");
      } else {
        console.log('ELSE');
         $(this).addClass("border-red");
      }
    })

    $('#id_contact_no').on('input blur paste', function() {
      $(this).val($(this).val().replace(/\D/g, ''))
      if($(this).val().length < 10 && $(this).val().length > 0) {
        $(this).addClass("border-red");
      } else {
        $(this).removeClass("border-red");
      }
    })
  });
</script>
<!--<script>-->
<!-- $(function() {-->
<!--    $("#month").on("keydown keyup", getDate);-->
<!--    function getDate() {-->
<!--        var now = new Date($("#id_start_date").val()-->
<!--        var num = Number($("#month").val()-->
<!--        $("#id_end_date").val(new Date(now.getFullYear(), now.getMonth()+num, 1););-->
<!--        console.log('HI');-->
<!--        }-->
<!--     });-->
<!--</script>-->
{% endblock %}

users/templates/error_404.html
{% extends 'base.html' %}
{% block base %}
<title>Error 404</title>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
            <div class="row flex-grow">
                <div class="col-lg-7 mx-auto text-white">
                    <div class="row align-items-center d-flex flex-row">
                        <div class="col-lg-6 text-lg-right pr-lg-4">
                            <h1 class="display-1 mb-0">404</h1>
                        </div>
                        <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                            <h2>SORRY!</h2>
                            <h3 class="font-weight-light">The page you’re looking for was not found.</h3>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12 text-center mt-xl-2">
                            <a class="text-white font-weight-medium" href="{% url 'dashboard' %}">Back to home</a>
                        </div>
                    </div>
<!--                    <div class="row mt-5">-->
<!--                        <div class="col-12 mt-xl-2">-->
<!--                            <p class="text-white font-weight-medium text-center">Copyright © 2018 All rights-->
<!--                                reserved.</p>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
{% endblock %}

users/templates/error_500.html
{% extends 'base.html' %}
{% block base %}
<title>Error 500</title>
<div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">500</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">Internal server error!</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="{% url 'dashboard' %}">Back to home</a>
                </div>
              </div>
<!--              <div class="row mt-5">-->
<!--                <div class="col-12 mt-xl-2">-->
<!--                  <p class="text-white font-weight-medium text-center">Copyright © 2018 All rights reserved.</p>-->
<!--                </div>-->
<!--              </div>-->
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% block base %}
<title>Login</title>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
            <div class="row flex-grow">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left p-5">
                        <div class="brand-logo">
                            <img src="{{baseImages}}/logo.svg">
                        </div>
                        <h4>Hello! let's get started</h4>
                        {% for msg in messages %}
                        <div id="deletesuccess"
                             class="alert
                     {% if msg.level == 20 %} alert-info {% endif %}
                     {% if msg.level == 25 %} alert-success {% endif %}
                     {% if msg.level == 30 %} alert-warning {% endif %}
                     {% if msg.level == 40 %} alert-danger {% endif %}"
                             role="alert">
                            {{msg}}
                        </div>
                        {% endfor %}
                        <form class="pt-3" action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control form-control-lg" id="exampleInputEmail1"
                                       placeholder="Email or Mobile No." name="username" value="{{username}}" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control form-control-lg" id="exampleInputPassword1"
                                       placeholder="Password" name="password" required>
                            </div>
                            <div class="mt-3">
                                <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn">
                                    SIGN IN
                                </button>
                            </div>
                            <div class="my-2 d-flex justify-content-between align-items-center">
                                <div class="form-check">
                                    <label class="text-muted">
                                        <input type="checkbox" name="stay_login" value="True"> Keep me signed in </label>
                                </div>
                                <a href="#" class="auth-link text-black">Forgot password?</a>
                            </div>
                            <div class="text-center mt-4 font-weight-light"> Don't have an account? <a
                                    href="#" class="text-primary">Create</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
{% endblock %}

users/templates/register.html
{% extends 'index.html' %}
{% block index %}
<title>{{page | title  }} Customer</title>
<div class="page-header">
    <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                  <i class="mdi mdi-account-plus"></i>
                </span> {{page | title  }} Customer </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
    </nav>
</div>
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Fill the customer details</h4>
                <p class="card-description"> {{msg}} </p>
                <form id="form" class="forms-sample"  method="post">
                    {% csrf_token %}
                    <div class="row">
                        {% if page == 'register' or edit_type == 'basic' %}
                        <div class="col-lg-6">
                            <p class="card-description">Basic Details</p>
                            {{form_basic.as_p}}
                        </div>
                        {% endif %}
                        {% if page == 'register' or edit_type == 'status' %}
                        <div class="col-lg-6">
                            <p class="card-description">Customer Status </p>
                            {{form_status.as_p}}
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Membership</label>
                                <div class="col-sm-4">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status"
                                                   id="membershipRadios1" value="1" {% if status %} checked {% endif %}> Active </label>
                                    </div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status"
                                                   id="membershipRadios2" value="0" {% if not status %} checked {% endif %}> Inactive </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <!--                    {% for field in form %}-->
                    <!--                    <div class="form-group">-->
                    <!--                        <label>{{field.label}}</label>-->
                    <!--                        {{field}}-->
                    <!--                        {{field.error}}-->
                    <!--                    </div>-->
                    <!--                    {% endfor %}-->
                    {% if page == 'register' %}
                    <button type="submit" form="form" formaction="{% url 'register_customer' %}" formmethod="post" class="btn btn-gradient-primary mr-2">Submit</button>
                    {% elif page == 'update' %}
                     <button type="submit" form="form" formaction="{% url 'edit_customer_details' customer_id=customer_id edit_type=edit_type  %}" formmethod="post" class="btn btn-gradient-primary mr-2">Update</button>
                    {% endif %}
                    <button class="btn btn-light" formnovalidate name="cancel" value="cancel">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
 $(function() {
    $("#id_total_fees, #id_fees_paid").on("keydown keyup", subtract);
    function subtract() {
        $("#id_fees_remaining").val(Number($("#id_total_fees").val()) - Number($("#id_fees_paid").val()));
        }
     });

</script>
<!--<script>-->
<!-- $(function() {-->
<!--    $("#month").on("keydown keyup", getDate);-->
<!--    function getDate() {-->
<!--        var now = new Date($("#id_start_date").val()-->
<!--        var num = Number($("#month").val()-->
<!--        $("#id_end_date").val(new Date(now.getFullYear(), now.getMonth()+num, 1););-->
<!--        console.log('HI');-->
<!--        }-->
<!--     });-->
<!--</script>-->
{% endblock %}